#!/usr/bin/env python2
# -*- coding: utf-8 -*-
# -*- coding: utf-8 -*-
"""Functions:
      1. 
"""
from os import path
from collections import defaultdict
import re
import pickle # import csv

# import sys
# sys.path.append('/Users/hhuang2 (Deleted)/Documents/NGSProject/2017NGS/HLA_Sequence_Analysis/Python/')
from utils import IMGTtools, IMGTdbIO

__author__ = "Hu Huang"
__copyright__ = "Copyright 2017, Hu Huang"
__credits__ = ["Add names"]
__license__ = "GPL"
__version__ = "0.1-dev"
__maintainer__ = "Hu Huang"
__email__ = "hwangtiger@gmail.com"

def find_IMGT_alignment(filename, HLAtyping, header_line = 8):
    """
    Find the aligned
    """
    # Read alignment file
    alignment_list = read_IMGT_alignment(filename, header_line)
    
    HLAtyping_pattern = re.compile(re.escape(HLAtyping))  ## pattern - find HLA typing
    
    #######  read alignement line
    aligned_seq = "" 
    for lines in alignment_list:
        if HLAtyping in HLAtyping_pattern.findall(lines): ## find the exact matching
            aligned_seq += re.sub(" ", "", re.sub(re.escape(HLAtyping), "", lines.rstrip()))
            break
        
    ## check if the HLA typing has the exact matching alignment
    if aligned_seq == "": ### if the HLA typing is not found in the list
        ##### find the
        aligned_typing_seq = re.sub("\.", "-", aligned_seq)  
        
    else:
        
        aligned_typing_seq = re.sub("\.", "-", aligned_seq)
    
    return(aligned_typing_seq)

def save_load_IMGTdb(HLA_locus = "A", fp='../data/'):
    """
    """
    fname = 'HLA_' + HLA_locus + '_IMGTdb'
    if path.exists(fp+fname): # if exist, load the data
        IMGTdbIO.load_IMGTdb(fname, fp)
    else:    # if not, then save the data
        IMGTdbIO.IMBTdb_2_dict(HLA_gene = "A", input_fp = "../IMGTHLA/")